### ISSUE TITLE
fleece cowl is not available for crafting

### ISSUE THREAD

**Issue by ducksarentrea1** [TheDevv/ClothingBlueprints#1]

**Comment by ds5678** [comment]
Do you know the name of this item? IE `GEAR_Something`

**Comment by Hotklou2404** [comment]
It has been fixed in the 1.2.0 update. Several other missing/broken items have also been fixed/added. The whole mod has also received a complete rebalance to material costs and crafting times. It's not near perfect, but it's a good start.
